Baitapthuchanh/Areas/Admin/Controllers/OrderController.cs
using Baitapthuchanh.Models;
using Baitapthuchanh.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Baitapthuchanh.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
    public class OrderController : Controller
    {
        private readonly DataContext _dataContext;

        public OrderController(DataContext context)
        {
            _dataContext = context;
        }


        public async Task<IActionResult> Index()
        {
            var orders = await _dataContext.Orders.OrderByDescending(p => p.Id).ToListAsync();
            int totalOrders = orders.Count();
            ViewBag.TotalOrders = totalOrders;
            return View(orders);
        }
    }
}

Baitapthuchanh/Controllers/CategoryController.cs
using Baitapthuchanh.Models;
using Baitapthuchanh.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Baitapthuchanh.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductRepository _productRepository;

        public CategoryController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryRepository.GetAllAsync();
            return View(categories);
        }

        public async Task<IActionResult> Display(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            var products = await _productRepository.GetByCategoryIdAsync(id);
            ViewBag.Category = category;
            return View(products);
        }
    }
}

Baitapthuchanh/Areas/Admin/Views/Order/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Don Hang";
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Order code</th>
            <th scope="col">UserName</th>

            <th scope="col">Order Date</th>
            <th scope="col">Order Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.Ordercode</th>
                <td>@item.UserName</td>
                <td>@item.CreatedDate</td>
                
                <td>
                    @if (item.Status == 1)
                    {
                        <span> class="text text-success">don hang moi</span>
                    }
                    else
                    {
                        <span> class="text text-danger">Don hang thanh cong</span>

                    }

                </td>


                <td>
                    <a asp-action="View" class="btn btn-warning btn-sm" asp-controller="Order" asp-route-Id="@item.Ordercode">Sửa</a>
                    <a asp-action="Delete" class="btn btn-danger btn-sm" asp-controller="Category" asp-route-Id="@item.Id">Xóa</a>
                </td>

            </tr>
        }


    </tbody>
</table>
<h2>Tổng số đơn hàng: @ViewBag.TotalOrders</h2>